-- ---------------------------------------------------------------------------
-- spritz-ops — the 22 finished perfumes.
--
-- GENERATED by scripts/seed-skus.mjs from spritz-site/lib/scents.ts.
-- Do not edit by hand: change the catalogue there and regenerate, or the shop
-- and the ERP start disagreeing about what a bottle is called.
--
-- shopify_variant_id is empty until the products exist in Shopify admin. P1
-- fills it from the sync; until then the column is NULL and the order sync has
-- nothing to match on, which is exactly the state the storefront is in too.
-- ---------------------------------------------------------------------------

insert into public.skus (key, name, inspired_by, family, accent, size, price_cents, shopify_variant_id)
values
  ('mer-bergamote', 'âme de mer et bergamote', 'Armani Acqua di Gio Parfum', 'fresh', '#3bc7f9', '50ml', 10000, NULL),
  ('citron-cardamome', 'éclat de citron et cardamome', 'Azzaro Wanted', 'fresh', '#c8d32b', '50ml', 10000, NULL),
  ('cognac-bergamote', 'essence de cognac et bergamote', 'Kilian Angels'' Share On The Rocks', 'warm', '#d58335', '50ml', 10000, NULL),
  ('amande-tonka', 'âme de amande et tonka', 'Carolina Herrera Good Girl Velvet Fatale', 'sweet', '#7c1a3a', '50ml', 10000, NULL),
  ('cedre-menthe', 'bois de cèdre et menthe', 'Chanel Bleu de Chanel', 'fresh', '#35b68d', '50ml', 10000, NULL),
  ('ylang-jasmin', 'voile de ylang et jasmin', 'Chanel No. 5', 'floral', '#c99b2d', '50ml', 10000, NULL),
  ('ananas-bouleau', 'voile d''ananas et bouleau', 'Creed Absolu Aventus', 'fresh', '#dac249', '50ml', 10000, NULL),
  ('oud-safran', 'bois de oud et safran', 'Creed Oud Zarian', 'warm', '#c97d2b', '50ml', 10000, NULL),
  ('gardenia-mandarin', 'bouquet de gardénia et mandarin', 'Gucci Flora Gorgeous Gardenia Intense', 'floral', '#fda654', '50ml', 10000, NULL),
  ('cerise-rose', 'voile de cerise et rose', 'Kayali Lovefest Burning Cherry', 'sweet', '#fa7db3', '50ml', 10000, NULL),
  ('iris-bergamote', 'âme de iris et bergamote', 'Lancôme La Vie Est Belle', 'sweet', '#c66a8b', '50ml', 10000, NULL),
  ('safran-ambre', 'essence de safran et ambre', 'MFK Baccarat Rouge 540', 'warm', '#951929', '50ml', 10000, NULL),
  ('jasmin-cashmeran', 'essence de jasmin et cashmeran', 'Mugler Alien Extraintense', 'floral', '#8b54a5', '50ml', 10000, NULL),
  ('cuir-menthe', 'voile de cuir et menthe', 'Paco Rabanne 1 Million Gold for Him', 'warm', '#6b492e', '50ml', 10000, NULL),
  ('poivre-ambre', 'voile de poivre noir et ambre', 'Paco Rabanne Invictus Victory', 'warm', '#136a39', '50ml', 10000, NULL),
  ('oud-santal', 'bois de oud et santal', 'Tom Ford Oud Wood', 'warm', '#c97d5a', '50ml', 10000, NULL),
  ('menthe-tonka', 'éclat de menthe et tonka', 'Versace Eros', 'fresh', '#69c788', '50ml', 10000, NULL),
  ('rose-jasmin', 'essence de rose et jasmin', 'Xerjoff Alexandria II', 'floral', '#b5268c', '50ml', 10000, NULL),
  ('lavande-vanille', 'fleur de lavande et vanille', 'YSL Libre', 'floral', '#8f7fc4', '50ml', 10000, NULL),
  ('truffe-chocolat', 'nuit de truffe et chocolat', 'Tom Ford Black Orchid', 'sweet', '#6c4225', '50ml', 10000, NULL),
  ('cuir-tabac', 'feu de cuir et tabac', 'Viktor & Rolf Spicebomb Dark Leather', 'warm', '#8a4a22', '50ml', 10000, NULL),
  ('vanille-cafe', 'noir de vanille et café', 'YSL Black Opium', 'sweet', '#caa42b', '50ml', 10000, NULL)
on conflict (key) do update set
  name               = excluded.name,
  inspired_by        = excluded.inspired_by,
  family             = excluded.family,
  accent             = excluded.accent,
  size               = excluded.size,
  price_cents        = excluded.price_cents,
  shopify_variant_id = coalesce(excluded.shopify_variant_id, skus.shopify_variant_id);

-- The consent for this seed: 22 bottles, no more, no fewer. If the catalogue
-- grows, this number moves with it — deliberately, not silently.
do $$
declare n integer;
begin
  select count(*) into n from public.skus;
  if n <> 22 then
    raise exception 'expected 22 SKUs after seeding, found %', n;
  end if;
end $$;
