#!/usr/bin/env node
/**
 * Writes the SKU seed migration from spritz-site/lib/scents.ts.
 *
 * The catalogue has exactly one source of truth and it is that file — it is
 * what the shop renders from. Retyping the 22 names into SQL would create a
 * second one, and the two would disagree the first time a label changes. So
 * the migration is generated, and regenerating it is how a change reaches the
 * database.
 *
 *   node scripts/seed-skus.mjs
 *
 * Node 24 imports the .ts file directly, so this reads the real objects rather
 * than parsing the source with regexes.
 *
 * The result is an upsert: re-running the migration updates names, colours and
 * Shopify ids without touching anything that references a SKU.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { SCENTS } from "../../spritz-site/lib/scents.ts";

const OPS = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(OPS, "supabase", "migrations", "0004_seed_skus.sql");

/** Postgres string literal. Null stays NULL rather than becoming ''. */
const q = (v) => (v === undefined || v === null || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

/** EUR in the catalogue, cents in the database. Whole euros, so no rounding. */
const cents = (eur) => Math.round(eur * 100);

const rows = SCENTS.map((s) =>
  `  (${q(s.key)}, ${q(s.name)}, ${q(s.inspiredBy)}, ${q(s.family)}, ${q(s.accent)}, ` +
  `${q(s.size)}, ${cents(s.price)}, ${q(s.shopifyVariantId)})`,
).join(",\n");

const sql = `-- ---------------------------------------------------------------------------
-- spritz-ops — the 22 finished perfumes.
--
-- GENERATED by scripts/seed-skus.mjs from spritz-site/lib/scents.ts.
-- Do not edit by hand: change the catalogue there and regenerate, or the shop
-- and the ERP start disagreeing about what a bottle is called.
--
-- shopify_variant_id is empty until the products exist in Shopify admin. P1
-- fills it from the sync; until then the column is NULL and the order sync has
-- nothing to match on, which is exactly the state the storefront is in too.
-- ---------------------------------------------------------------------------

insert into public.skus (key, name, inspired_by, family, accent, size, price_cents, shopify_variant_id)
values
${rows}
on conflict (key) do update set
  name               = excluded.name,
  inspired_by        = excluded.inspired_by,
  family             = excluded.family,
  accent             = excluded.accent,
  size               = excluded.size,
  price_cents        = excluded.price_cents,
  shopify_variant_id = coalesce(excluded.shopify_variant_id, skus.shopify_variant_id);

-- The consent for this seed: 22 bottles, no more, no fewer. If the catalogue
-- grows, this number moves with it — deliberately, not silently.
do $$
declare n integer;
begin
  select count(*) into n from public.skus;
  if n <> ${SCENTS.length} then
    raise exception 'expected ${SCENTS.length} SKUs after seeding, found %', n;
  end if;
end $$;
`;

writeFileSync(OUT, sql);
console.log(`[seed-skus] wrote ${SCENTS.length} SKUs -> supabase/migrations/0004_seed_skus.sql`);
