#!/usr/bin/env node
/**
 * Writes the SKU seed migration from spritz-site/lib/scents.ts.
 *
 * Two rows per scent: the 50ml, and the 15ml that only ships inside a set.
 * The sets themselves are NOT rows here — a set deducts stock from these two
 * singles (catalog spec §1), so giving it its own inventory would double-count
 * the same glass.
 *
 * The catalogue has exactly one source of truth and it is that file — it is
 * what the shop renders from. Retyping the 22 names into SQL would create a
 * second one, and the two would disagree the first time a label changes. So
 * the migration is generated, and regenerating it is how a change reaches the
 * database.
 *
 *   node scripts/seed-skus.mjs
 *
 * Node 24 imports the .ts file directly, so this reads the real objects rather
 * than parsing the source with regexes.
 *
 * The result is an upsert: re-running the migration updates names, colours and
 * Shopify ids without touching anything that references a SKU.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { SCENTS } from "../../spritz-site/lib/scents.ts";
import { ML_15_PRICE } from "../../spritz-site/lib/sizes.ts";

const OPS = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(OPS, "supabase", "migrations", "0004_seed_skus.sql");

/** Postgres string literal. Null stays NULL rather than becoming ''. */
const q = (v) => (v === undefined || v === null || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

/** EUR in the catalogue, cents in the database. Whole euros, so no rounding. */
const cents = (eur) => Math.round(eur * 100);

/** Every stock-keeping bottle: each scent in 50ml, and again in 15ml. */
const bottles = SCENTS.flatMap((s) => [
  {
    key: s.key,
    name: s.name,
    size: s.size,
    price: s.price,
    variantId: s.shopifyVariantId,
    scent: s,
  },
  {
    key: `${s.key}-15ml`,
    name: `${s.name} (15ml)`,
    size: "15ml",
    price: ML_15_PRICE,
    variantId: s.ml15VariantId,
    scent: s,
  },
]);

const rows = bottles.map((b) =>
  `  (${q(b.key)}, ${q(b.name)}, ${q(b.scent.inspiredBy)}, ${q(b.scent.family)}, ${q(b.scent.accent)}, ` +
  `${q(b.size)}, ${cents(b.price)}, ${q(b.variantId)})`,
).join(",\n");

const sql = `-- ---------------------------------------------------------------------------
-- spritz-ops — the 22 finished perfumes, each in 50ml and 15ml.
--
-- GENERATED by scripts/seed-skus.mjs from spritz-site/lib/scents.ts.
-- Do not edit by hand: change the catalogue there and regenerate, or the shop
-- and the ERP start disagreeing about what a bottle is called.
--
-- shopify_variant_id is empty until the products exist in Shopify admin. P1
-- fills it from the sync; until then the column is NULL and the order sync has
-- nothing to match on, which is exactly the state the storefront is in too.
-- ---------------------------------------------------------------------------

insert into public.skus (key, name, inspired_by, family, accent, size, price_cents, shopify_variant_id)
values
${rows}
on conflict (key) do update set
  name               = excluded.name,
  inspired_by        = excluded.inspired_by,
  family             = excluded.family,
  accent             = excluded.accent,
  size               = excluded.size,
  price_cents        = excluded.price_cents,
  shopify_variant_id = coalesce(excluded.shopify_variant_id, skus.shopify_variant_id);

-- The consent for this seed: two rows per catalogue scent, no more, no fewer.
-- If the catalogue grows, this number moves with it — deliberately, not
-- silently. Sets are excluded on purpose: they deduct from these singles.
do $$
declare n integer;
begin
  select count(*) into n from public.skus;
  if n <> ${bottles.length} then
    raise exception 'expected ${bottles.length} SKUs after seeding, found %', n;
  end if;
end $$;
`;

writeFileSync(OUT, sql);
console.log(`[seed-skus] wrote ${bottles.length} SKUs (${SCENTS.length} scents × 50ml + 15ml) -> supabase/migrations/0004_seed_skus.sql`);
